-- MySQL Script generated by MySQL Workbench
-- Wed 29 May 2024 05:32:44 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOS` DEFAULT CHARACTER SET utf8 ;
USE `SOS` ;

-- -----------------------------------------------------
-- Table `SOS`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`service_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`service_providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `national_id` VARCHAR(45) NOT NULL,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `national_id_UNIQUE` (`national_id` ASC) VISIBLE,
  INDEX `fk_service_providers_services1_idx` (`services_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_providers_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `SOS`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`documents` (
  `link` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_providers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documents_service_providers_idx` (`service_providers_id` ASC) VISIBLE,
  CONSTRAINT `fk_documents_service_providers`
    FOREIGN KEY (`service_providers_id`)
    REFERENCES `SOS`.`service_providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`users` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) unique NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_type` enum('admin','customer','service_provider') default 'customer' NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `SOS`.`contact` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO services (service_name) VALUES ('Plumbing'), ('Electrical'), ('Cleaning'), ('Painting');

