-- MySQL Script generated by MySQL Workbench
-- Wed 29 May 2024 05:32:44 AM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOS` DEFAULT CHARACTER SET utf8 ;
USE `SOS` ;

-- -----------------------------------------------------
-- Table `SOS`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(255) NOT NULL,
  `available` BOOLEAN NOT NULL DEFAULT TRUE,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`service_providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`service_providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `national_id` VARCHAR(45) NOT NULL,
  `services_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `national_id_UNIQUE` (`national_id` ASC) VISIBLE,
  INDEX `fk_service_providers_services1_idx` (`services_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_providers_services1`
    FOREIGN KEY (`services_id`)
    REFERENCES `SOS`.`services` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`documents` (
  `link` TEXT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_providers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documents_service_providers_idx` (`service_providers_id` ASC) VISIBLE,
  CONSTRAINT `fk_documents_service_providers`
    FOREIGN KEY (`service_providers_id`)
    REFERENCES `SOS`.`service_providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOS`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`users` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) unique NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_type` enum('admin','customer','service_provider') default 'customer' NOT NULL
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SOS`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`contact` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- Table `SOS`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOS`.`reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `service_provider_id` INT NOT NULL,
  `reservation_time` DATETIME NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
    ON DELETE CASCADE,
  FOREIGN KEY (`service_id`) REFERENCES `services`(`id`)
    ON DELETE CASCADE,
  FOREIGN KEY (`service_provider_id`) REFERENCES `service_providers`(`id`)
    ON DELETE CASCADE
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insert a sample admin user
INSERT INTO users (full_name, email, password, user_type) VALUES ('Admin User', 'admin@example.com', SHA2('admin_password', 256), 'admin');

-- Insert a sample service provider user
INSERT INTO users (full_name, email, password, user_type) VALUES ('Service Provider', 'provider@example.com', SHA2('provider_password', 256), 'service_provider');

-- Insert a sample customer user
INSERT INTO users (full_name, email, password, user_type) VALUES ('Customer User', 'customer@example.com', SHA2('customer_password', 256), 'customer');

-- Insert sample services
INSERT INTO services (service_name, available) VALUES ('Plumbing', 1), ('Electrical', 1), ('Cleaning', 1), ('Painting', 1);

-- Insert sample service providers
INSERT INTO service_providers (full_name, email, phone, address, national_id, services_id) VALUES 
('John Doe', 'john@example.com', '1234567890', '123 Main St', 'A123456789', 1),
('Jane Smith', 'jane@example.com', '0987654321', '456 Elm St', 'B987654321', 2);
